if(my_module_Qt_included)
return()
endif(my_module_Qt_included)
set(my_module_Qt_included true)

if(EXISTS ${ODK_ROOT}/3rdparty/qt)
    message(STATUS "Qt rcc found")
    set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${ODK_ROOT}/3rdparty/qt/cmake)
    set(Qt5Core_RCC_EXECUTABLE ${ODK_ROOT}/3rdparty/qt/bin/rcc.exe)
    include(Qt5CoreMacros)
else()
    find_package(Qt5Core REQUIRED)
    message(STATUS "Qt found")
endif()
