name: Linux build with minimal dependencies

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Install minimal requirements
      run: sudo apt-get install -yq qt5-default
    - uses: actions/checkout@v4
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=g++
    - name: Build
      run: cmake --build ${{github.workspace}}/build --target all --parallel
